### ISSUE TITLE
Can't use "Statistics"

### ISSUE THREAD

**Issue by liaralabs** [repslet/nightwalker#2]
Hey! Great work on the theme. Much easier on the eyes.

I noticed after a quick look through that the View > "Statistics" option seems to be missing from the menu. Is this something that accidentally broke in the theme? I use this feature a lot!

![image](https://user-images.githubusercontent.com/30909703/104269610-92f8ee80-544b-11eb-942e-d3ebf8292548.png)

![image](https://user-images.githubusercontent.com/30909703/104269647-a6a45500-544b-11eb-8fd7-f242b946aefb.png)

**Comment by repslet** [comment]
Fixed with #32e714e71d626d0914c25de524359f3f5329494e
